package org.sailcbi.APIServer.Entities.EntityDefinitions

import com.coleji.neptune.Storable.FieldValues._
import com.coleji.neptune.Storable.Fields._
import com.coleji.neptune.Storable._
import com.coleji.neptune.Util.Initializable

class PersonsTemp extends StorableClass(PersonsTemp) {
	override object values extends ValuesObject {
		val personId = new IntFieldValue(self, PersonsTemp.fields.personId)
		val nameFirst = new NullableStringFieldValue(self, PersonsTemp.fields.nameFirst)
		val nameMiddleInitial = new NullableStringFieldValue(self, PersonsTemp.fields.nameMiddleInitial)
		val nameLast = new NullableStringFieldValue(self, PersonsTemp.fields.nameLast)
		val namePrefix = new NullableStringFieldValue(self, PersonsTemp.fields.namePrefix)
		val nameSuffix = new NullableStringFieldValue(self, PersonsTemp.fields.nameSuffix)
		val gender = new NullableStringFieldValue(self, PersonsTemp.fields.gender)
		val dob = new NullableDateTimeFieldValue(self, PersonsTemp.fields.dob)
		val email = new NullableStringFieldValue(self, PersonsTemp.fields.email)
		val parentEmail = new NullableStringFieldValue(self, PersonsTemp.fields.parentEmail)
		val addr1 = new NullableStringFieldValue(self, PersonsTemp.fields.addr1)
		val addr2 = new NullableStringFieldValue(self, PersonsTemp.fields.addr2)
		val addr3 = new NullableStringFieldValue(self, PersonsTemp.fields.addr3)
		val city = new NullableStringFieldValue(self, PersonsTemp.fields.city)
		val state = new NullableStringFieldValue(self, PersonsTemp.fields.state)
		val zip = new NullableStringFieldValue(self, PersonsTemp.fields.zip)
		val country = new NullableStringFieldValue(self, PersonsTemp.fields.country)
		val phonePrimary = new NullableStringFieldValue(self, PersonsTemp.fields.phonePrimary)
		val phonePrimaryType = new NullableStringFieldValue(self, PersonsTemp.fields.phonePrimaryType)
		val phoneAlternate = new NullableStringFieldValue(self, PersonsTemp.fields.phoneAlternate)
		val phoneAlternateType = new NullableStringFieldValue(self, PersonsTemp.fields.phoneAlternateType)
		val emerg1Name = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1Name)
		val emerg1Relation = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1Relation)
		val emerg1PhonePrimary = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1PhonePrimary)
		val emerg1PhoneAlternate = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1PhoneAlternate)
		val emerg2Name = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2Name)
		val emerg2Relation = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2Relation)
		val emerg2PhonePrimary = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2PhonePrimary)
		val emerg2PhoneAlternate = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2PhoneAlternate)
		val allergies = new NullableStringFieldValue(self, PersonsTemp.fields.allergies)
		val medications = new NullableStringFieldValue(self, PersonsTemp.fields.medications)
		val specialNeeds = new NullableStringFieldValue(self, PersonsTemp.fields.specialNeeds)
		val badMail = new NullableBooleanFieldValue(self, PersonsTemp.fields.badMail)
		val deceased = new NullableBooleanFieldValue(self, PersonsTemp.fields.deceased)
		val doNotCall = new NullableBooleanFieldValue(self, PersonsTemp.fields.doNotCall)
		val doNotEmail = new NullableBooleanFieldValue(self, PersonsTemp.fields.doNotEmail)
		val doNotMail = new NullableBooleanFieldValue(self, PersonsTemp.fields.doNotMail)
		val occupation = new NullableStringFieldValue(self, PersonsTemp.fields.occupation)
		val employer = new NullableStringFieldValue(self, PersonsTemp.fields.employer)
		val matchingGifts = new NullableStringFieldValue(self, PersonsTemp.fields.matchingGifts)
		val citizenship = new NullableStringFieldValue(self, PersonsTemp.fields.citizenship)
		val ethnicity = new NullableStringFieldValue(self, PersonsTemp.fields.ethnicity)
		val language = new NullableStringFieldValue(self, PersonsTemp.fields.language)
		val referralSource = new NullableStringFieldValue(self, PersonsTemp.fields.referralSource)
		val sailingExp = new NullableStringFieldValue(self, PersonsTemp.fields.sailingExp)
		val organization = new NullableStringFieldValue(self, PersonsTemp.fields.organization)
		val orgContact = new NullableStringFieldValue(self, PersonsTemp.fields.orgContact)
		val student = new NullableBooleanFieldValue(self, PersonsTemp.fields.student)
		val school = new NullableStringFieldValue(self, PersonsTemp.fields.school)
		val createdOn = new NullableDateTimeFieldValue(self, PersonsTemp.fields.createdOn)
		val createdBy = new NullableStringFieldValue(self, PersonsTemp.fields.createdBy)
		val updatedOn = new NullableDateTimeFieldValue(self, PersonsTemp.fields.updatedOn)
		val updatedBy = new NullableStringFieldValue(self, PersonsTemp.fields.updatedBy)
		val ethnicityOther = new NullableStringFieldValue(self, PersonsTemp.fields.ethnicityOther)
		val referralOther = new NullableStringFieldValue(self, PersonsTemp.fields.referralOther)
		val allowSignouts = new NullableBooleanFieldValue(self, PersonsTemp.fields.allowSignouts)
		val sendAlert = new NullableBooleanFieldValue(self, PersonsTemp.fields.sendAlert)
		val temp = new StringFieldValue(self, PersonsTemp.fields.temp)
		val personType = new NullableDoubleFieldValue(self, PersonsTemp.fields.personType)
		val emerg1PhonePrimaryType = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1PhonePrimaryType)
		val emerg1PhoneAlternateType = new NullableStringFieldValue(self, PersonsTemp.fields.emerg1PhoneAlternateType)
		val emerg2PhonePrimaryType = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2PhonePrimaryType)
		val emerg2PhoneAlternateType = new NullableStringFieldValue(self, PersonsTemp.fields.emerg2PhoneAlternateType)
		val badPhone = new NullableBooleanFieldValue(self, PersonsTemp.fields.badPhone)
		val badEmail = new NullableBooleanFieldValue(self, PersonsTemp.fields.badEmail)
		val military = new NullableStringFieldValue(self, PersonsTemp.fields.military)
		val reducedLunch = new NullableBooleanFieldValue(self, PersonsTemp.fields.reducedLunch)
		val pwHash = new NullableStringFieldValue(self, PersonsTemp.fields.pwHash)
		val incomeLevel = new NullableDoubleFieldValue(self, PersonsTemp.fields.incomeLevel)
		val newReturning = new NullableBooleanFieldValue(self, PersonsTemp.fields.newReturning)
		val swimProof = new NullableDoubleFieldValue(self, PersonsTemp.fields.swimProof)
		val oldFundraisingGreeting = new NullableStringFieldValue(self, PersonsTemp.fields.oldFundraisingGreeting)
		val oldPhoneWork = new NullableStringFieldValue(self, PersonsTemp.fields.oldPhoneWork)
		val languageOther = new NullableStringFieldValue(self, PersonsTemp.fields.languageOther)
	}
}

object PersonsTemp extends StorableObject[PersonsTemp] {
	override val useRuntimeFieldnamesForJson: Boolean = true

	override val entityName: String = "PERSONS_TEMP"

	object fields extends FieldsObject {
		val personId = new IntDatabaseField(self, "PERSON_ID")
		val nameFirst = new NullableStringDatabaseField(self, "NAME_FIRST", 100)
		val nameMiddleInitial = new NullableStringDatabaseField(self, "NAME_MIDDLE_INITIAL", 5)
		val nameLast = new NullableStringDatabaseField(self, "NAME_LAST", 100)
		val namePrefix = new NullableStringDatabaseField(self, "NAME_PREFIX", 50)
		val nameSuffix = new NullableStringDatabaseField(self, "NAME_SUFFIX", 50)
		val gender = new NullableStringDatabaseField(self, "GENDER", 1)
		val dob = new NullableDateTimeDatabaseField(self, "DOB")
		val email = new NullableStringDatabaseField(self, "EMAIL", 100)
		val parentEmail = new NullableStringDatabaseField(self, "PARENT_EMAIL", 100)
		val addr1 = new NullableStringDatabaseField(self, "ADDR_1", 200)
		val addr2 = new NullableStringDatabaseField(self, "ADDR_2", 200)
		val addr3 = new NullableStringDatabaseField(self, "ADDR_3", 200)
		val city = new NullableStringDatabaseField(self, "CITY", 50)
		val state = new NullableStringDatabaseField(self, "STATE", 50)
		val zip = new NullableStringDatabaseField(self, "ZIP", 15)
		val country = new NullableStringDatabaseField(self, "COUNTRY", 50)
		val phonePrimary = new NullableStringDatabaseField(self, "PHONE_PRIMARY", 100)
		val phonePrimaryType = new NullableStringDatabaseField(self, "PHONE_PRIMARY_TYPE", 50)
		val phoneAlternate = new NullableStringDatabaseField(self, "PHONE_ALTERNATE", 30)
		val phoneAlternateType = new NullableStringDatabaseField(self, "PHONE_ALTERNATE_TYPE", 50)
		val emerg1Name = new NullableStringDatabaseField(self, "EMERG1_NAME", 200)
		val emerg1Relation = new NullableStringDatabaseField(self, "EMERG1_RELATION", 50)
		val emerg1PhonePrimary = new NullableStringDatabaseField(self, "EMERG1_PHONE_PRIMARY", 100)
		val emerg1PhoneAlternate = new NullableStringDatabaseField(self, "EMERG1_PHONE_ALTERNATE", 100)
		val emerg2Name = new NullableStringDatabaseField(self, "EMERG2_NAME", 200)
		val emerg2Relation = new NullableStringDatabaseField(self, "EMERG2_RELATION", 50)
		val emerg2PhonePrimary = new NullableStringDatabaseField(self, "EMERG2_PHONE_PRIMARY", 100)
		val emerg2PhoneAlternate = new NullableStringDatabaseField(self, "EMERG2_PHONE_ALTERNATE", 100)
		val allergies = new NullableStringDatabaseField(self, "ALLERGIES", 4000)
		val medications = new NullableStringDatabaseField(self, "MEDICATIONS", 4000)
		val specialNeeds = new NullableStringDatabaseField(self, "SPECIAL_NEEDS", 4000)
		val badMail = new NullableBooleanDatabaseField(self, "BAD_MAIL")
		val deceased = new NullableBooleanDatabaseField(self, "DECEASED")
		val doNotCall = new NullableBooleanDatabaseField(self, "DO_NOT_CALL")
		val doNotEmail = new NullableBooleanDatabaseField(self, "DO_NOT_EMAIL")
		val doNotMail = new NullableBooleanDatabaseField(self, "DO_NOT_MAIL")
		val occupation = new NullableStringDatabaseField(self, "OCCUPATION", 100)
		val employer = new NullableStringDatabaseField(self, "EMPLOYER", 100)
		val matchingGifts = new NullableStringDatabaseField(self, "MATCHING_GIFTS", 1)
		val citizenship = new NullableStringDatabaseField(self, "CITIZENSHIP", 100)
		val ethnicity = new NullableStringDatabaseField(self, "ETHNICITY", 100)
		val language = new NullableStringDatabaseField(self, "LANGUAGE", 100)
		val referralSource = new NullableStringDatabaseField(self, "REFERRAL_SOURCE", 200)
		val sailingExp = new NullableStringDatabaseField(self, "SAILING_EXP", 100)
		val organization = new NullableStringDatabaseField(self, "ORGANIZATION", 100)
		val orgContact = new NullableStringDatabaseField(self, "ORG_CONTACT", 200)
		val student = new NullableBooleanDatabaseField(self, "STUDENT")
		val school = new NullableStringDatabaseField(self, "SCHOOL", 100)
		val createdOn = new NullableDateTimeDatabaseField(self, "CREATED_ON")
		val createdBy = new NullableStringDatabaseField(self, "CREATED_BY", 500)
		val updatedOn = new NullableDateTimeDatabaseField(self, "UPDATED_ON")
		val updatedBy = new NullableStringDatabaseField(self, "UPDATED_BY", 500)
		val ethnicityOther = new NullableStringDatabaseField(self, "ETHNICITY_OTHER", 100)
		val referralOther = new NullableStringDatabaseField(self, "REFERRAL_OTHER", 100)
		val allowSignouts = new NullableBooleanDatabaseField(self, "ALLOW_SIGNOUTS")
		val sendAlert = new NullableBooleanDatabaseField(self, "SEND_ALERT")
		val temp = new StringDatabaseField(self, "TEMP", 1)
		val personType = new NullableDoubleDatabaseField(self, "PERSON_TYPE")
		val emerg1PhonePrimaryType = new NullableStringDatabaseField(self, "EMERG1_PHONE_PRIMARY_TYPE", 50)
		val emerg1PhoneAlternateType = new NullableStringDatabaseField(self, "EMERG1_PHONE_ALTERNATE_TYPE", 50)
		val emerg2PhonePrimaryType = new NullableStringDatabaseField(self, "EMERG2_PHONE_PRIMARY_TYPE", 50)
		val emerg2PhoneAlternateType = new NullableStringDatabaseField(self, "EMERG2_PHONE_ALTERNATE_TYPE", 50)
		val badPhone = new NullableBooleanDatabaseField(self, "BAD_PHONE")
		val badEmail = new NullableBooleanDatabaseField(self, "BAD_EMAIL")
		val military = new NullableStringDatabaseField(self, "MILITARY", 50)
		val reducedLunch = new NullableBooleanDatabaseField(self, "REDUCED_LUNCH")
		val pwHash = new NullableStringDatabaseField(self, "PW_HASH", 100)
		val incomeLevel = new NullableDoubleDatabaseField(self, "INCOME_LEVEL")
		val newReturning = new NullableBooleanDatabaseField(self, "NEW_RETURNING")
		val swimProof = new NullableDoubleDatabaseField(self, "SWIM_PROOF")
		val oldFundraisingGreeting = new NullableStringDatabaseField(self, "OLD_FUNDRAISING_GREETING", 300)
		val oldPhoneWork = new NullableStringDatabaseField(self, "OLD_PHONE_WORK", 50)
		val languageOther = new NullableStringDatabaseField(self, "LANGUAGE_OTHER", 200)
	}

	def primaryKey: IntDatabaseField = fields.personId
}