package org.sailcbi.APIServer.Api.Endpoints.Dto.Member.ApCancelTeachInstance

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */


case class MemberApCancelTeachInstancePostRequestDto (
	instanceId: Int,
)

object MemberApCancelTeachInstancePostRequestDto {
	implicit val format = Json.format[MemberApCancelTeachInstancePostRequestDto]
	def apply(v: JsValue): MemberApCancelTeachInstancePostRequestDto
		= v.as[MemberApCancelTeachInstancePostRequestDto]
}

