package org.sailcbi.APIServer.Api.Endpoints.Dto.Member.ApCancelTeachInstance

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */


case class DtoMemberApCancelTeachInstancePostRequest (
	instanceId: Int,
)

object DtoMemberApCancelTeachInstancePostRequest {
	implicit val format = Json.format[DtoMemberApCancelTeachInstancePostRequest]
	def apply(v: JsValue): DtoMemberApCancelTeachInstancePostRequest
		= v.as[DtoMemberApCancelTeachInstancePostRequest]
}

