package org.sailcbi.APIServer.Api.Endpoints.Dto.Staff.Rest.ApClassSessions.Today

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */
case class StaffRestApClassSessionsTodayGetResponseSuccessDto (
	sessionId: Double,
	instanceId: Double,
	headcount: Option[Double],
	cancelledDatetime: Option[String],
	sessionDatetime: String,
	sessionLength: Double,
	isMakeup: Option[Boolean],
	$$apClassInstance: StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance,
)

case class StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance (
	instanceId: Double,
	cancelledDatetime: Option[String],
	signupsStartOverride: Option[String],
	signupMin: Option[Double],
	price: Option[Double],
	signupMax: Option[Double],
	formatId: Double,
	hideOnline: Option[Boolean],
	cancelByOverride: Option[String],
	locationString: Option[String],
	doNotAutoCancel: Option[Boolean],
	$$apClassSignups: List[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups],
)

case class StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups (
	instanceId: Double,
	discountInstanceId: Option[Double],
	voidedOnline: Option[Boolean],
	personId: Double,
	orderId: Option[Double],
	price: Option[Double],
	signupId: Double,
	closeId: Option[Double],
	sequence: Double,
	paymentMedium: Option[String],
	ccTransNum: Option[String],
	paymentLocation: Option[String],
	voidCloseId: Option[Double],
	signupType: String,
	signupNote: Option[String],
	signupDatetime: String,
	$$person: StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person,
	$$apClassWaitlistResult: Option[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult],
)

case class StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person (
	personId: Double,
	nameFirst: Option[String],
	nameLast: Option[String],
)

object StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person {
	implicit val format = Json.format[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person]
	def apply(v: JsValue): StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person
		= v.as[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person]
}

case class StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult (
	wlResult: String,
	foVmDatetime: Option[String],
	offerExpDatetime: String,
	signupId: Double,
	foAlertDatetime: String,
	permitOvercrowd: Option[Boolean],
)

object StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult {
	implicit val format = Json.format[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult]
	def apply(v: JsValue): StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult
		= v.as[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult]
}

object StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups {
	implicit val StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_PersonFormat
		= StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_Person.format
	implicit val StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResultFormat
		= StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups_ApClassWaitlistResult.format
	implicit val format = Json.format[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups]
	def apply(v: JsValue): StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups
		= v.as[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups]
}

object StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance {
	implicit val StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignupsFormat
		= StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance_ApClassSignups.format
	implicit val format = Json.format[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance]
	def apply(v: JsValue): StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance
		= v.as[StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance]
}

object StaffRestApClassSessionsTodayGetResponseSuccessDto {
	implicit val StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstanceFormat
		= StaffRestApClassSessionsTodayGetResponseSuccessDto_ApClassInstance.format
	implicit val format = Json.format[StaffRestApClassSessionsTodayGetResponseSuccessDto]
	def apply(v: JsValue): StaffRestApClassSessionsTodayGetResponseSuccessDto
		= v.as[StaffRestApClassSessionsTodayGetResponseSuccessDto]
}

