package org.sailcbi.APIServer.Api.Endpoints.Dto.Member.ApClassInstancesInstructorInfo

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */
case class DtoMemberApClassInstancesInstructorInfoGetResponseSuccess (
	instanceId: Int,
	instructorName: Option[String],
	signupCt: Int,
	signupMin: Option[Int],
	signupMax: Option[Int],
)

object DtoMemberApClassInstancesInstructorInfoGetResponseSuccess {
	implicit val format = Json.format[DtoMemberApClassInstancesInstructorInfoGetResponseSuccess]
	def apply(v: JsValue): DtoMemberApClassInstancesInstructorInfoGetResponseSuccess
		= v.as[DtoMemberApClassInstancesInstructorInfoGetResponseSuccess]
}

