package org.sailcbi.APIServer.Api.Endpoints.Dto.Staff.Rest.ApClassTypes

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */
case class DtoStaffRestApClassTypesGetResponseSuccess (
	typeId: Int,
	typeName: String,
	ratingPrereq: Option[Int],
	classPrereq: Option[Int],
	ratingOverkill: Option[Int],
	displayOrder: Double,
	descLong: String,
	descShort: Option[String],
	classOverkill: Option[Int],
	noSignup: Boolean,
	priceDefault: Option[Double],
	signupMaxDefault: Option[Int],
	signupMinDefault: Option[Int],
	disallowIfOverkill: Boolean,
	$$apClassFormats: List[DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats],
)

case class DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats (
	formatId: Int,
	typeId: Int,
	description: Option[String],
	priceDefaultOverride: Option[Double],
	sessionCtDefault: Int,
	sessionLengthDefault: Double,
	signupMaxDefaultOverride: Option[Int],
	signupMinDefaultOverride: Option[Int],
)

object DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats {
	implicit val format = Json.format[DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats]
	def apply(v: JsValue): DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats
		= v.as[DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats]
}

object DtoStaffRestApClassTypesGetResponseSuccess {
	implicit val DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormatsFormat
		= DtoStaffRestApClassTypesGetResponseSuccess_ApClassFormats.format
	implicit val format = Json.format[DtoStaffRestApClassTypesGetResponseSuccess]
	def apply(v: JsValue): DtoStaffRestApClassTypesGetResponseSuccess
		= v.as[DtoStaffRestApClassTypesGetResponseSuccess]
}

