package org.sailcbi.APIServer.Api.Endpoints.Dto.Staff.Rest.ApClassInstances.ThisSeason

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */
case class StaffRestApClassInstancesThisSeasonGetResponseSuccessDto (
	instanceId: Double,
	cancelledDatetime: Option[String],
	signupsStartOverride: Option[String],
	signupMin: Option[Double],
	price: Option[Double],
	signupMax: Option[Double],
	formatId: Double,
	hideOnline: Option[Boolean],
	cancelByOverride: Option[String],
	locationString: Option[String],
	doNotAutoCancel: Option[Boolean],
	instructorId: Option[Double],
	$$apClassSessions: List[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions],
	$$instructor: Option[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor],
)

case class StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions (
	sessionId: Double,
	instanceId: Double,
	headcount: Option[Double],
	cancelledDatetime: Option[String],
	sessionDatetime: String,
	sessionLength: Double,
	isMakeup: Option[Boolean],
)

object StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions {
	implicit val format = Json.format[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions]
	def apply(v: JsValue): StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions
		= v.as[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions]
}

case class StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor (
	personId: Double,
	nameFirst: Option[String],
	nameLast: Option[String],
)

object StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor {
	implicit val format = Json.format[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor]
	def apply(v: JsValue): StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor
		= v.as[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor]
}

object StaffRestApClassInstancesThisSeasonGetResponseSuccessDto {
	implicit val StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessionsFormat
		= StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_ApClassSessions.format
	implicit val StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_InstructorFormat
		= StaffRestApClassInstancesThisSeasonGetResponseSuccessDto_Instructor.format
	implicit val format = Json.format[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto]
	def apply(v: JsValue): StaffRestApClassInstancesThisSeasonGetResponseSuccessDto
		= v.as[StaffRestApClassInstancesThisSeasonGetResponseSuccessDto]
}

