package org.sailcbi.APIServer.Api.Endpoints.Dto.Sunset

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */
case class DtoSunsetGetResponseSuccess (
	forDate: String,
	twilightStart: String,
	sunrise: String,
	sunset: String,
	twilightEnd: String,
	dayLengthSeconds: Int,
	sonarNoon: String,
	nauticalTwilightStart: String,
	nauticalTwilightEnd: String,
	astronomicalTwilightStart: String,
	astronomicalTwilightEnd: String,
)

object DtoSunsetGetResponseSuccess {
	implicit val format = Json.format[DtoSunsetGetResponseSuccess]
	def apply(v: JsValue): DtoSunsetGetResponseSuccess
		= v.as[DtoSunsetGetResponseSuccess]
}

