package org.sailcbi.APIServer.Api.Endpoints.Dto.Member.ApTeachInstance

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */


case class MemberApTeachInstancePostRequestDto (
	instanceId: Int,
)

object MemberApTeachInstancePostRequestDto {
	implicit val format = Json.format[MemberApTeachInstancePostRequestDto]
	def apply(v: JsValue): MemberApTeachInstancePostRequestDto
		= v.as[MemberApTeachInstancePostRequestDto]
}

