package org.sailcbi.APIServer.Api.Endpoints.Dto.Member.ApTeachInstance

import play.api.libs.json.{JsValue, Json}

/**
 * !!!!!!!!!!!!
 * This file is AUTO-GENERATED by cbidb-schema
 * Do not manually alter this file, or your changes will be lost
 * !!!!!!!!!!!!
 */


case class DtoMemberApTeachInstancePostRequest (
	instanceId: Int,
)

object DtoMemberApTeachInstancePostRequest {
	implicit val format = Json.format[DtoMemberApTeachInstancePostRequest]
	def apply(v: JsValue): DtoMemberApTeachInstancePostRequest
		= v.as[DtoMemberApTeachInstancePostRequest]
}

